autojudge/urls.py
"""
autojudge URL Configuration.
"""
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/judge/')),
    path('judge/', include('judge.urls')),
    path('admin/', admin.site.urls),
]

judge/urls.py
from django.urls import path
from django.conf.urls import include
from django.contrib.auth.views import LoginView, LogoutView

from . import views
from . import apps

app_name = apps.JudgeConfig.name
handler404 = views.handler404
handler500 = views.handler500

urlpatterns = [
    # General-purpose paths
    path('', views.index, name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('auth/', include('social_django.urls', namespace='social')),

    # Contest-specific paths
    path('contest/new/', views.new_contest, name='new_contest'),
    path('contest/<int:contest_id>/', views.contest_detail, name='contest_detail'),
    path('contest/<int:contest_id>/scores/', views.contest_scores_csv, name='contest_scores_csv'),
    path('contest/<int:contest_id>/delete/', views.delete_contest, name='delete_contest'),
    path('contest/<int:contest_id>/problem/new/',
         views.new_problem, name='new_problem'),
    path('contest/<int:contest_id>/poster/new/',
         views.add_poster, name='contest_add_poster'),
    path('contest/<int:contest_id>/participant/new/',
         views.add_participant, name='contest_add_participant'),
    path('contest/<int:contest_id>/posters/',
         views.get_posters, name='get_posters'),
    path('contest/<int:contest_id>/participants/',
         views.get_participants, name='get_participants'),

    # Problem-specific paths
    path('problem/<str:problem_id>/', views.problem_detail, name='problem_detail'),
    path('problem/<str:problem_id>/delete/', views.delete_problem, name='delete_problem'),
    path('problem/<str:problem_id>/starting-code/',
         views.problem_starting_code, name='problem_starting_code'),
    path('problem/<str:problem_id>/compilation-script/',
         views.problem_compilation_script, name='problem_compilation_script'),
    path('problem/<str:problem_id>/test-script/',
         views.problem_test_script, name='problem_test_script'),
    path('problem/default-scripts/<str:script_name>/',
         views.problem_default_script, name='problem_default_script'),
    path('problem/<str:problem_id>/edit/',
         views.edit_problem, name='edit_problem'),
    path('problem/<str:problem_id>/submissions/',
         views.problem_submissions, name='problem_submissions'),

    # Submission-specific paths
    path('submission/<str:submission_id>/',
         views.submission_detail, name='submission_detail'),
    path('submission/<str:submission_id>/download/',
         views.submission_download, name='submission_download'),
    path('problem/<str:problem_id>/testcase/<str:testcase_id>/delete/',
         views.delete_testcase, name='delete_testcase'),
]

judge/models.py
from django.db import models

from uuid import uuid4
from os.path import splitext
from functools import partial
from datetime import timedelta
from django.utils import timezone


def starting_code_name(instance, filename):
    return 'content/problems/{}/start_code{}'.format(instance.code, splitext(filename)[1])


def compilation_test_upload_location(instance, filename, is_compilation):
    # We disregard the filename argument
    file_prefix = 'compilation' if is_compilation else 'test'
    file_extension = '.sh' if is_compilation else ''
    file_name = '{}_script{}'.format(file_prefix, file_extension)
    return 'content/problems/{}/{}'.format(instance.code, file_name)


def testcase_upload_location(instance, filename, is_input):
    # We disregard the filename argument
    file_prefix = 'input' if is_input else 'output'
    file_name = '{}file_{}.txt'.format(file_prefix, instance.id)
    return 'content/testcase/{}'.format(file_name)


def submission_upload_location(instance, filename):
    # We disregard the filename argument
    file_name = 'submission_{}{}'.format(instance.id, instance.file_type)
    return 'content/submissions/{}'.format(file_name)


def comment_upload_location(instance, filename):
    # We disregard the filename argument
    return 'content/comment/{}.yml'.format(instance.id)


class Contest(models.Model):
    """
    Model for Contest.
    """

    name = models.CharField(
        max_length=50, default='Unnamed Contest', unique=True)
    """Contest name"""

    start_datetime = models.DateTimeField()
    """Start Date and Time for Contest"""

    soft_end_datetime = models.DateTimeField()
    """"Soft" End Date and Time for Contest"""

    hard_end_datetime = models.DateTimeField()
    """"Hard" End Date and Time for Contest"""

    penalty = models.FloatField(default=0.0)
    """Penalty for late-submission"""

    public = models.BooleanField(default=False)
    """Is the contest public?"""

    enable_linter_score = models.BooleanField(default=True)
    """Enable linter scoring"""

    enable_poster_score = models.BooleanField(default=True)
    """Enable poster scoring"""

    def __str__(self):
        return self.name


class Problem(models.Model):
    """
    Model for a Problem.
    """
    # UNSET is a special problem code which other problems must not use.
    code = models.CharField(max_length=10, primary_key=True, default='UNSET')
    """Problem code"""

    contest = models.ForeignKey(Contest, on_delete=models.CASCADE, null=True)
    """Foreign key to contest for the problem"""

    name = models.CharField(max_length=50, default='Name not set')
    """Problem name"""

    statement = models.TextField(default='The problem statement is empty.')
    """Problem statement"""

    input_format = models.TextField(default='No input format specified.')
    """Problem input format"""

    output_format = models.TextField(default='No output format specified.')
    """Problem output format"""

    difficulty = models.PositiveSmallIntegerField(default=0)
    """Problem difficulty"""

    time_limit = models.DurationField(default=timedelta(seconds=10))
    """Problem time limit"""

    # Currently this is specified in mega-bytes
    memory_limit = models.PositiveIntegerField(default=200000)
    """Problem memory limit"""

    # Support upto 30 file formats
    file_exts = models.CharField(max_length=100, default='.py,.cpp')
    """Accepted file extensions for submissions to problem"""

    starting_code = models.FileField(upload_to=starting_code_name, null=True)
    """Problem starting code"""

    max_score = models.PositiveSmallIntegerField(default=0)
    """Maximum score for a test case for the problem"""

    compilation_script = models.FileField(
        upload_to=partial(compilation_test_upload_location,
                          is_compilation=True),
        default='./default/compilation_script.sh')
    """Problem compilation script"""

    test_script = models.FileField(
        upload_to=partial(compilation_test_upload_location,
                          is_compilation=False),
        default='./default/test_script.sh')
    """Problem test script"""

    def __str__(self):
        return self.code


class Person(models.Model):
    """
    Model for Person.
    """

    email = models.EmailField(primary_key=True)
    """Email ID of the Person"""

    rank = models.PositiveIntegerField(default=0)
    """Rank of the Person"""

    def __str__(self):
        return self.email


class Submission(models.Model):
    """
    Model for a Submission.
    """
    # Self Generated PrimaryKey
    id = models.CharField(max_length=36, primary_key=True, default=uuid4)

    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    """Foreign key to problem for which this is a submission"""

    participant = models.ForeignKey(Person, on_delete=models.CASCADE)
    """Foreign key to person who submitted the solution"""

    # This has to be updated periodically
    PERMISSIBLE_FILE_TYPES = (
        ('.none', 'NOT_SELECTED'),
        ('.c', 'C'),
        ('.cpp', 'C++'),
        ('.py', 'Python3.6'),
        ('.go', 'Go'),
        ('.hs', 'Haskell'),
    )

    file_type = models.CharField(
        max_length=5, choices=PERMISSIBLE_FILE_TYPES, default='.none')
    """File type of submission"""

    submission_file = models.FileField(upload_to=submission_upload_location)
    """Submission file"""

    timestamp = models.DateTimeField()
    """Timestamp of submission"""

    judge_score = models.PositiveSmallIntegerField(default=0)
    """Judge score"""

    poster_score = models.SmallIntegerField(default=0)
    """Poster score"""

    linter_score = models.FloatField(default=0.0)
    """Linter score"""

    final_score = models.FloatField(default=0.0)
    """Final score"""


class ContestPerson(models.Model):
    """
    Model for ContestPerson.
    This maps how (either as a Participant or Poster) persons have access to the contests.
    """

    contest = models.ForeignKey(Contest, on_delete=models.CASCADE)
    """Foreign key to contest in which this person is taking part"""

    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    """Foreign key to the actual person"""

    # True for Poster and False for Participant
    role = models.BooleanField()
    """Determines if Person is a Poster or a Participant"""

    class Meta:
        unique_together = (('contest', 'person'),)


class TestCase(models.Model):
    """
    Model for TestCase.
    Maintains testcases and mapping between TestCase and Problem.
    """

    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    """Foreign key to problem for which this is a test case"""

    # True for Public and False for Private
    public = models.BooleanField()
    """Determines if the test case is a public test case or a private test case"""

    # Self Generated PrimaryKey
    id = models.CharField(max_length=36, primary_key=True, default=uuid4)

    # Sample: ./content/testcase/inputfile_UUID.txt
    inputfile = models.FileField(upload_to=partial(testcase_upload_location, is_input=True),
                                 default='./default/inputfile.txt')
    """Input file for the test case"""

    # ./content/testcase/outputfile_UUID.txt
    outputfile = models.FileField(upload_to=partial(testcase_upload_location, is_input=False),
                                  default='./default/outputfile.txt')
    """Output file for the test case"""


class SubmissionTestCase(models.Model):
    """
    Model for SubmissionTestCase.
    Maintains mapping between TestCase and Submission.
    """

    # Possible Verdicts
    VERDICT = (
        ('F', 'Failed'),
        ('P', 'Passed'),
        ('R', 'Running'),
        ('TE', 'Time Limit Exceeded'),
        ('ME', 'Out Of Memory'),
        ('CE', 'Compilation Error'),
        ('RE', 'Runtime Error'),
        ('NA', 'Internal Failure'))

    submission = models.ForeignKey(Submission, on_delete=models.CASCADE)
    """Foreign key to submission"""

    testcase = models.ForeignKey(TestCase, on_delete=models.CASCADE)
    """Foreign key to test case"""

    verdict = models.CharField(max_length=2, choices=VERDICT, default='NA')
    """Verdict by the judge"""

    memory_taken = models.PositiveIntegerField()
    """Virtual memory consumed by the submission"""

    time_taken = models.DurationField()
    """Time taken by the submission"""

    message = models.TextField(default='')
    """Message placeholder, used for erroneous submissions"""

    class Meta:
        unique_together = (('submission', 'testcase'),)


class Comment(models.Model):
    """
    Model for Comment.
    """

    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    """Foreign key to problem relating to the comment"""

    person = models.ForeignKey(
        Person, on_delete=models.CASCADE, related_name='person')
    """Foreign key to person"""

    # Self Generated PrimaryKey
    id = models.CharField(max_length=36, primary_key=True, default=uuid4)

    commenter = models.ForeignKey(
        Person, on_delete=models.CASCADE, related_name='commenter')
    """Foreign key to person who commented"""

    timestamp = models.DateTimeField(default=timezone.now)
    """Timestamp of the comment"""

    comment = models.TextField()
    """Content of the comment"""


class PersonProblemFinalScore(models.Model):
    """
    Model to store the final score assigned to a person for a problem.
    """

    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    """Foreign key to problem for which the score is saved"""

    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    """Foreign key to person whose submission's score is saved"""

    score = models.FloatField(default=0.0)
    """Final score saved"""

    class Meta:
        unique_together = (('problem', 'person'),)

judge/templates/judge/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Home{% endblock %} | AUTOJUDGE</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">

    <!-- Icons -->
    <link href="/static/assets/vendor/nucleo/css/nucleo.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
        integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <!-- Theme CSS -->
    <link type="text/css" href="/static/assets/css/argon.min.css" rel="stylesheet">

    <style>
        .ql-editor strong {
            font-weight: bold;
        }
    </style>
    {% block styles %}
    {% endblock %}
</head>

<body>
    {% url 'judge:index' as homepage %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-default">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ homepage }}">AUTOJUDGE</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-default"
                aria-controls="navbar-default" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbar-default">
                <div class="navbar-collapse-header">
                    <div class="row">
                        <div class="col-6 collapse-brand">
                            <a href="{{ homepage }}">
                                LOGO
                                <!-- TODO -->
                            </a>
                        </div>
                        <div class="col-6 collapse-close">
                            <button type="button" class="navbar-toggler" data-toggle="collapse"
                                data-target="#navbar-default" aria-controls="navbar-default" aria-expanded="false"
                                aria-label="Toggle navigation">
                                <span></span>
                                <span></span>
                            </button>
                        </div>
                    </div>
                </div>
                <ul class="navbar-nav mr-lg-auto">
                    {% block navlink %}
                    {% endblock %}
                </ul>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        {% if user.is_superuser %}
                            <li class="nav-item">
                                <a class="nav-link" href="#" data-toggle="tooltip" data-placement="bottom"
                                    title="{{ user.email }}">Hi Superuser <b>{{ user.get_username }}</b></a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="#" data-toggle="tooltip" data-placement="bottom"
                                    title="{{ user.email }}">Hi <b>{{ user.get_full_name }}</b></a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="btn btn-neutral btn-icon" href="{% url 'judge:logout' %}"><span
                                    class="btn-inner--icon">
                                    <i class="fas fa-sign-out-alt mr-2 mb-1"></i>
                                </span>
                                <span class="nav-link-inner--text">Log out</span></a>
                        </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="btn btn-neutral btn-icon" href="{% url 'judge:social:begin' 'google-oauth2' %}"><span
                                class="btn-inner--icon">
                                <i class="fas fa-sign-in-alt mr-2 mb-1"></i>
                            </span>
                            <span class="nav-link-inner--text">Log in</span></a>
                    </li>
                    {% endif %}
                    {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="btn btn-warning btn-icon" href="/admin/" target="_blank"><span
                                class="btn-inner--icon">
                                <i class="fas fa-sign-in-alt mr-2 mb-1"></i>
                            </span>
                            <span class="nav-link-inner--text">Administration</span></a>
                    </li>
                    {% endif %}
                </ul>
            </div>

        </div>
    </nav>
    <div class="container">
        {% if request.path != homepage %}
        <nav aria-label="breadcrumb" class="my-4">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ homepage }}">Home</a></li>
                {% block breadcrumb %}
                {% endblock %}
            </ol>
        </nav>
        {% endif %}
        <div class="row my-4">
            <div class="col-12">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

    <!-- Core -->
    <script src="/static/assets/vendor/jquery/jquery.min.js"></script>
    <script src="/static/assets/vendor/popper/popper.min.js"></script>
    <script src="/static/assets/vendor/bootstrap/bootstrap.min.js"></script>

    <!-- Theme JS -->
    <script src="/static/assets/js/argon.min.js"></script>
    <script>
        $(document).ready(() => {
            $(function () {
                $('[data-toggle="tooltip"]').tooltip()
            })
        })
    </script>
    {% block scripts %}
    {% endblock %}
</body>

</html>

judge/templates/judge/contest_add_person.html
{% extends 'judge/base.html' %}

{% block title %}Add {{ type }} | Contest {{ contest_id }}{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'judge:contest_detail' contest_id %}">Contest {{ contest_id }}</a></li>
{% if type == 'Poster' %}
<li class="breadcrumb-item"><a href="{% url 'judge:get_posters' contest_id %}">Posters</a></li>
{% endif %}
{% if type == 'Participant' %}
<li class="breadcrumb-item"><a href="{% url 'judge:get_participants' contest_id %}">Participants</a></li>
{% endif %}
<li class="breadcrumb-item active" aria-current="page">Add {{ type }}</li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-12">
        <h2>Add {{ type }}</h2>
    </div>
    <div class="col-12">
        <form method="POST">
            {% if form.non_field_errors %}
            {% for nfe in form.non_field_errors %}
            <div class="alert alert-danger mt-2" role="alert">
                    {{ nfe }}
            </div>
            {% endfor %}
            {% endif %}
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text|safe }}</small>
                {% endif %}
                {% if field.errors %}
                {% for fe in field.errors %}
                <div class="alert alert-danger mt-2" role="alert">
                    {{ fe|striptags }}
                </div>
                {% endfor %}
                {% endif %}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Add {{ type }}</button>
        </form>
    </div>
</div>
{% endblock %}

judge/templates/judge/contest_persons.html
{% extends 'judge/base.html' %}

{% block title %}{{ type }}s | Contest {{ contest_id }}{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'judge:contest_detail' contest_id %}">Contest {{ contest_id }}</a></li>
<li class="breadcrumb-item active" aria-current="page">{{ type }}s</li>
{% endblock %}

{% block scripts %}
<script>
    $('.autojudge-delete-person').click(function (){
        $('#id_email').val($(this).attr('data-email'))
        $('#autojudge-delete-form').submit();
    })
</script>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-12">
        <h2 class="d-inline">{{ type }}s</h2>
        {% if permission %}
        {% if type == 'Poster' %}
        <a class="btn btn-primary float-right" href="{% url 'judge:contest_add_poster' contest_id %}">Add Poster</a>
        {% else %}
        <a class="btn btn-primary float-right" href="{% url 'judge:contest_add_participant' contest_id %}">Add Participant</a>
        {% endif %}
        {% endif %}
    </div>
    <div class="col-12">
        <form method="POST" id="autojudge-delete-form">{% csrf_token %}
            {% if form.non_field_errors %}
            {% for nfe in form.non_field_errors %}
            <div class="alert alert-danger mt-2" role="alert">
                    {{ nfe }}
            </div>
            {% endfor %}
            {% endif %}
            {% for field in form %}
                {{ field }}
            {% endfor %}
        </form>
        <div class="list-group">
            {% for person in persons %}
            <div class="list-group-item">
                <span>{{ person }}</span>
                {% if permission %}
                <button class="btn btn-danger float-right autojudge-delete-person" data-email="{{ person }}"><i class="fas fa-trash"></i></button>
                {% endif %}
            </div>
            {% empty %}
            <p>There are no {{ type|lower }}s for this contest.</p>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

judge/templates/judge/edit_problem.html
{% extends "judge/base.html" %}

{% block title %}Edit Problem {{ problem.code }} | Contest {{ contest.pk }}{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'judge:contest_detail' contest.pk %}">Contest {{ contest.pk }}</a></li>
<li class="breadcrumb-item"><a href="{% url 'judge:problem_detail' problem.code %}">Problem {{ problem.code }}</a></li>
<li class="breadcrumb-item active" aria-current="page">Edit</li>
{% endblock %}

{% block styles %}
<link href="/static/assets/vendor/quill/quill.snow.css" rel="stylesheet">
{% endblock %}

{% block scripts %}
<script src="/static/assets/vendor/quill/quill.js"></script>
<script>
    let quillModules = {
        toolbar: [
            ['bold', 'italic'],
            ['link', 'blockquote', 'code-block'],
            [{ list: 'ordered' }, { list: 'bullet' }],
        ]
    }

    let statementQuill = new Quill('#statementEditor', {
        modules: quillModules,
        theme: 'snow',
    })

    let inputFormatQuill = new Quill('#inputFormatEditor', {
        modules: quillModules,
        theme: 'snow',
    })

    let outputFormatQuill = new Quill('#outputFormatEditor', {
        modules: quillModules,
        theme: 'snow',
    })

    {% if problem.statement != None %}
    statementQuill.setContents(JSON.parse('{{ problem.statement | escapejs }}'))
    {% endif %}
    {% if problem.input_format != None %}
    inputFormatQuill.setContents(JSON.parse('{{ problem.input_format | escapejs }}'))
    {% endif %}
    {% if problem.output_format != None %}
    outputFormatQuill.setContents(JSON.parse('{{ problem.output_format | escapejs }}'))
    {% endif %}

    $('form').submit(function (e) {
        $('#id_statement').val(JSON.stringify(statementQuill.getContents()))
        $('#id_input_format').val(JSON.stringify(inputFormatQuill.getContents()))
        $('#id_output_format').val(JSON.stringify(outputFormatQuill.getContents()))
    })
</script>
{% endblock %}

{% block content %}
<div class="row my-2">
    <div class="col-12">
        <h2>Edit Problem</h2>
    </div>
</div>
<div class="row">
    <div class="col-12 col-md-8">
        <form action="{% url 'judge:edit_problem' problem.code %}" method="POST">
            {% if form.non_field_errors %}
            {% for nfe in form.non_field_errors %}
            <div class="alert alert-danger mt-2" role="alert">
                    {{ nfe }}
            </div>
            {% endfor %}
            {% endif %}
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }} {{ field }}
                {% if field.name == 'statement' %}
                <div id="statementEditor"></div>
                {% endif %}
                {% if field.name == 'input_format' %}
                <div id="inputFormatEditor"></div>
                {% endif %}
                {% if field.name == 'output_format' %}
                <div id="outputFormatEditor"></div>
                {% endif %}
                {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text|safe }}</small>
                {% endif %}
                {% if field.errors %}
                <div class="alert alert-danger mt-2" role="alert">
                    {{ field.errors|striptags }}
                </div>
                {% endif %}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
{% endblock %}

judge/templates/judge/index.html
{% extends "judge/base.html" %}

{% block content %}
<div class="row">
    <div class="col-12">
        <h1 class="d-inline-block">Contests</h1>
        {% if user.is_authenticated %}
        <a class="btn btn-icon btn-primary float-right" href="{% url 'judge:new_contest' %}">
            <span class="btn-inner--icon"><i class="fas fa-plus"></i></span>
            <span class="btn-inner--text">New Contest</span>
        </a>
        {% endif %}
    </div>
    <div class="col-12">
        {% for contest, permission in contests %}
        {% if permission != None %}
        <!-- TODO Handle when all are None -->
        <div class="card my-3">
            <div class="card-body">
                <div>
                    <h4 class="d-inline-block">{{ contest.name }}</h4>
                    <div class="float-right">
                        {% if contest.public %}<span class="badge badge-success">Public</span>{% else %}
                        <span class="badge badge-default">Private</span>{% endif %}
                        {% if permission %}<span class="badge badge-warning">Poster</span>
                        {% else %}<span class="badge badge-warning">Participant</span>{% endif %}
                    </div>
                </div>
                <a href="{% url 'judge:contest_detail' contest.pk %}" class="card-link">Go to contest page</a>
            </div>
        </div>
        {% endif %}
        {% empty %}
        <div class="col-12">
            No active contests for the time being. Create a new contest or check later.
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

judge/templates/judge/new_problem.html
{% extends "judge/base.html" %}

{% block title %}New Problem | Contest {{ contest.pk }}{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'judge:contest_detail' contest.pk %}">Contest {{ contest.pk }}</a></li>
<li class="breadcrumb-item active" aria-current="page">New Problem</li>
{% endblock %}

{% block styles %}
<link href="/static/assets/vendor/quill/quill.snow.css" rel="stylesheet">
{% endblock %}

{% block scripts %}
<script src="/static/assets/vendor/quill/quill.js"></script>
<script>
    let quillModules = {
        toolbar: [
            ['bold', 'italic'],
            ['link', 'blockquote', 'code-block'],
            [{ list: 'ordered' }, { list: 'bullet' }],
        ]
    }

    let statementQuill = new Quill('#statementEditor', {
        modules: quillModules,
        theme: 'snow',
    })

    let inputFormatQuill = new Quill('#inputFormatEditor', {
        modules: quillModules,
        theme: 'snow',
    })

    let outputFormatQuill = new Quill('#outputFormatEditor', {
        modules: quillModules,
        theme: 'snow',
    })

    $(document).ready(function(){
        statementQuill.setContents(JSON.parse($('#id_statement').val()))
        inputFormatQuill.setContents(JSON.parse($('#id_input_format').val()))
        outputFormatQuill.setContents(JSON.parse($('#id_output_format').val()))
    })

    $('form').submit(function (e) {
        $('#id_statement').val(JSON.stringify(statementQuill.getContents()))
        $('#id_input_format').val(JSON.stringify(inputFormatQuill.getContents()))
        $('#id_output_format').val(JSON.stringify(outputFormatQuill.getContents()))
    })
</script>
{% endblock %}

{% block content %}
<div class="row my-2">
    <div class="col-12">
        <h2>New Problem</h2>
    </div>
</div>
<div class="row">
    <div class="col-12 col-md-8">
        <form action="{% url 'judge:new_problem' contest.pk %}" method="POST" enctype="multipart/form-data">
            {% if form.non_field_errors %}
            <div class="alert alert-danger alter-dismissible fade show" role="alert">
                {{ form.non_field_errors }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }} {{ field }}
                {% if field.name == 'statement' %}
                <div id="statementEditor"></div>
                {% endif %}
                {% if field.name == 'input_format' %}
                <div id="inputFormatEditor"></div>
                {% endif %}
                {% if field.name == 'output_format' %}
                <div id="outputFormatEditor"></div>
                {% endif %}
                {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text|safe }}</small>
                {% endif %}
                {% if field.name == 'compilation_script' or field.name == 'test_script' %}
                <small class="form-text text-muted">The default script can be downloaded from <a href="{% url 'judge:problem_default_script' field.name %}">here.</a></small>
                {% endif %}
                {% if field.errors %}
                <div class="alert alert-danger mt-2" role="alert">
                    {{ field.errors|striptags }}
                </div>
                {% endif %}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
</div>
{% endblock %}